### ISSUE TITLE
Question/Suggestion/Request: Create custom database JSON for Downloader script. 

### ISSUE THREAD

**Issue by NML32** [uberyoji/mister-boot-roms#1]
Is it possible to create a custom-database JSON file so the Downloader script could download and install your mister-boot-roms?
Info about custom database JSON file creation: https://github.com/MiSTer-devel/Downloader_MiSTer/blob/main/docs/custom-databases.md

Hopefully, this would allow for automatic download via the Downloader script. 

Thank you creating these custom boot ROMS.

**Comment by uberyoji** [comment]
Sure. Let me look into it later tonight.

**Comment by uberyoji** [comment]
So sorry. It took me a month but it is finally here!

Just add the following to  /media/fat/downloader.ini:

```
[uberyoji_mister_boot_roms]
db_url = https://raw.githubusercontent.com/uberyoji/mister-boot-roms/main/db/uberyoji_mister_boot_roms.json
```

**Comment by NML32** [comment]
Thank you!!
