### ISSUE TITLE
Bootrom download on SD card even with CIFS

### ISSUE THREAD

**Issue by GamaBurst** [uberyoji/mister-boot-roms#3]
When using the update_all script to download the bootrom files, all the bootrom files are automatically placed on the games folder on the sd card even if the games folder is located on a NAS using CIFS. Normally the bootrom files should be downloaded directly to the games folder on the NAS when using CIFS.

**Comment by uberyoji** [comment]
Can you share your cifs ini config? I have many mister and one of them is configured to use my NAS. It works properly on my end.
Here is part of my config:

```
LOCAL_DIR="*"

#Optional additional mount options, when in doubt leave blank.
#If you have problems not related to username/password, you can try "vers=2.0" or "vers=3.0".
ADDITIONAL_MOUNT_OPTIONS="vers=2.0"

#"true" in order to wait for the CIFS server to be reachable;
#useful when using this script at boot time.
WAIT_FOR_SERVER="true"

#"true" for automounting CIFS shares at boot time;
#it will create start/kill scripts in /etc/network/if-up.d and /etc/network/if-down.d.
MOUNT_AT_BOOT="false"


#========= ADVANCED OPTIONS =========
BASE_PATH="/media/fat"
#MISTER_CIFS_URL="https://github.com/MiSTer-devel/CIFS_MiSTer"
KERNEL_MODULES="md4.ko|md5.ko|des_generic.ko|fscache.ko|cifs.ko"
IFS="|"
SINGLE_CIFS_CONNECTION="true"
#Pipe "|" separated list of directories which will never be mounted when LOCAL_DIR="*"
SPECIAL_DIRECTORIES="config|linux|System Volume Information"
```

**Comment by uberyoji** [comment]
Please share also your downloader.ini config.

**Comment by GamaBurst** [comment]
**Here's my cifs.ini config :**

SERVER="NASDS1821"
SHARE="MiSTer"
SHARE_DIRECTORY=""
USERNAME="mister1"
PASSWORD="!dsgdfgsdf"
DOMAIN=""
LOCAL_DIR="cifs"
ADDITIONAL_MOUNT_OPTIONS=""
WAIT_FOR_SERVER="true"
MOUNT_AT_BOOT="true"

**Here's the downloader.ini config :**

[mister]

[distribution_mister]
db_url = https://raw.githubusercontent.com/MiSTer-devel/Distribution_MiSTer/main/db.json.zip

[jtcores]
db_url = https://raw.githubusercontent.com/jotego/jtcores_mister/main/jtbindb.json.zip

[bios_db]
db_url = https://raw.githubusercontent.com/theypsilon/BiosDB_MiSTer/db/bios_db.json

[atrac17/Coin-Op_Collection]
db_url = https://raw.githubusercontent.com/atrac17/Coin-Op_Collection/db/db.json.zip

[names_txt]
db_url = https://raw.githubusercontent.com/ThreepwoodLeBrush/Names_MiSTer/dbs/names_CHAR28_Manufacturer_US.json

[arcade_roms_db]
db_url = https://raw.githubusercontent.com/theypsilon/ArcadeROMsDB_MiSTer/db/arcade_roms_db.json.zip

[bgm]
db_url = 'https://raw.githubusercontent.com/wizzomafizzo/MiSTer_BGM/main/bgm.json'

[RGarciaLago/MGL_Core_Setnames]
db_url = https://raw.githubusercontent.com/RGarciaLago/MGL_Core_Setnames/db/db.json.zip

[uberyoji_mister_boot_roms]
db_url = https://raw.githubusercontent.com/uberyoji/mister-boot-roms/main/db/uberyoji_mister_boot_roms.json

**Comment by uberyoji** [comment]
Sorry it took me a while to get back to this. I think I found the solution. Can you try the staging.json instead and test for me? So replace with staging.json in your ini file.

[uberyoji_mister_boot_roms]
db_url = https://raw.githubusercontent.com/uberyoji/mister-boot-roms/main/db/staging.json

**Comment by GamaBurst** [comment]
Hello,
Now it works perfectly!

I have tested the staging.json with a fresh new install and now the boot.rom files are downloaded in the right folder on the cifs mount.

Thank you! ;)

**Comment by uberyoji** [comment]
Excellent I will update the live db. Sorry again for the delay.
