### ISSUE TITLE
Megadrive/Genesis boot1.rom is an actual game

### ISSUE THREAD

**Issue by PapiFed** [uberyoji/mister-boot-roms#4]
Seems to be pulling in a Xenocrisis rom instead of your bootrom. You might want to check this out asap.

**Comment by uberyoji** [comment]
Thx I will check asap!

**Comment by uberyoji** [comment]
I confirm the DB is grabbing -> https://github.com/uberyoji/mister-boot-roms/releases/download/v.0.11/mister-boot.md
DB entry is:
  "|games/Genesis/boot1.rom": {
                "hash": "db6cabad069010368214b032d714efe5",
                "size": 131072,
                "url": "https://github.com/uberyoji/mister-boot-roms/releases/download/v.0.11/mister-boot.md",
                "tags": [],
                "overwrite": true,
                "reboot": false
            },
Which is the boot rom and not Xenocrisis. Are you sure you did not start XenoCrisis before? Which core are you using? The new MegaDrive NukeMD?

**Comment by uberyoji** [comment]
Also please let me know if you simlink the Genesis folder to MegaDrive folder.

**Comment by PapiFed** [comment]
Thanks for checking. I did not start Xenocrisis, I don’t even have that rom on my MicroSD. 
Using the old Core and no simlink, this is weird :-D
I deleted boot1.rom and ran update_all and the same happened again.

**Comment by uberyoji** [comment]
Can you share your downloader.ini content?

**Comment by PapiFed** [comment]
[MiSTer_SAM_files]
db_url = https://raw.githubusercontent.com/mrchrisster/MiSTer_SAM/db/db.json.zip

[distribution_mister]
db_url = https://raw.githubusercontent.com/MiSTer-devel/Distribution_MiSTer/main/db.json.zip

[jtcores]
db_url = https://raw.githubusercontent.com/jotego/jtcores_mister/main/jtbindb.json.zip
filter = [MiSTer]

[arcade_offset_folder]
db_url = https://raw.githubusercontent.com/atrac17/Arcade_Offset/db/arcadeoffsetdb.json.zip

[theypsilon_unofficial_distribution]
db_url = https://raw.githubusercontent.com/theypsilon/Distribution_Unofficial_MiSTer/main/unofficialdb.json.zip

[llapi_folder]
db_url = https://raw.githubusercontent.com/MiSTer-LLAPI/LLAPI_folder_MiSTer/main/llapidb.json.zip

[arcade_roms_db]
db_url = https://raw.githubusercontent.com/theypsilon/ArcadeROMsDB_MiSTer/db/arcade_roms_db.json.zip

[names_txt]
db_url = https://raw.githubusercontent.com/ThreepwoodLeBrush/Names_MiSTer/dbs/names_CHAR18_Common_JP.json

[bios_db]
db_url = https://raw.githubusercontent.com/theypsilon/BiosDB_MiSTer/db/bios_db.json

[atrac17/Coin-Op_Collection]
db_url = https://raw.githubusercontent.com/atrac17/Coin-Op_Collection/db/db.json.zip

[mrext/all]
db_url = https://raw.githubusercontent.com/wizzomafizzo/mrext/main/releases/all.json

[Ranny-Snice/Ranny-Snice-Wallpapers]
db_url = https://raw.githubusercontent.com/Ranny-Snice/Ranny-Snice-Wallpapers/db/db.json.zip
filter = ar4-3

[agg23_db]
db_url = https://raw.githubusercontent.com/agg23/mister-repository/db/manifest.json

[arcade_names_txt]
db_url = https://raw.githubusercontent.com/PigSaint/ArcadeNames_MiSTer/dbs/arcade_names_JP.json

[uberyoji_mister_boot_roms]
db_url = https://raw.githubusercontent.com/uberyoji/mister-boot-roms/main/db/uberyoji_mister_boot_roms.json

[mrext/remote]
db_url = https://github.com/wizzomafizzo/mrext/raw/main/releases/remote/remote.json

[RGarciaLago/VIDEO_PRESETS_by_Robby]
db_url = https://raw.githubusercontent.com/RGarciaLago/VIDEO_PRESETS_by_Robby/db/db.json.zip

**Comment by uberyoji** [comment]
I looked at all the DB entries including mine and I can't see where it would be coming from. Can you test the following:
- remove the [uberyoji_mister_boot_roms] DB section entirely
- delete boot1.rom or boot.rom (if it exsists but it should not) from the Genesis folder
- rerun the update all script
Send a printout of the update all log to see what is going on

**Comment by uberyoji** [comment]
Another thing to check on your end is if you have an external drive attached and/or NAS. Make sure to delete the boot1.rom and boot.rom from there as well before launching the update all script.

**Comment by PapiFed** [comment]
"remove the [uberyoji_mister_boot_roms] DB section entirely"
Do you mean remove the entry from the downloader.ini file ?

If yes then I did so and the files was NOT downloaded again after deleting it and running update_all however Xenocrisis is still being launched upon opening the Core
[update_all.zip](https://github.com/uberyoji/mister-boot-roms/files/12566638/update_all.zip)

I am not using any external drive nor NAS. I will start looking in the simlink direction... what else could it be !?!

**Comment by uberyoji** [comment]
Ok so if you removed the section from downloader.ini, removed the boot rom, confirmed the file are not downloaded and still get xenocrisis on boot, I'm not sure where it is coming from. Can you list the content of the games/Genesis folder?

**Comment by PapiFed** [comment]
Yep the problem is definitively not with your rom. I will close this issue.

Here is the content of the Genesis folder but I doubt the problem comes from here since I have another setup where I have a completely different content in that folder.
<img width="93" alt="image" src="https://github.com/uberyoji/mister-boot-roms/assets/62958761/743c0088-9fd2-4d85-b110-aa7062f27de5">

**Comment by PapiFed** [comment]
Found it ! it was bootrom/GENESIS.rom the culprit !
Sorry for having you spend time on this matter and a BIG thank you for your work on this boot roms, love them since day 1 !

**Comment by uberyoji** [comment]
Thank god you found it. I was pulling my hair out trying to find out where it came from.
Also thanks for letting me know :D
