### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by abishur** [uberyoji/mister-boot-roms#5]
I saw in the To Do section you plan to release the source code, could that be a high priority please? 😉

I love the ideal of the project but just wanted to make a plain background or very low key gif background for the boot.rom file.

**Comment by uberyoji** [comment]
I am not ready to release anything at the moment.

However, If you want to just have a simple background, you usually can just modify existing examples to achieve that goal.
For starters, check the following tool chains,
  - nesdoug/neslib for Nes
  - SGDK for Genesis 
  - GB studio for Gameboy
  - chilly willy for 32x
  - HuC for PC Engine
  - devkitSMS for Master System

Keep in mind however that none of these will let you import a gif (a any straight image) directly as all the platforms have different specs and format to deal with. Reading through the toolchain's documentation will provide good clues on how to handle background tiles loading and their format requirement.
