### ISSUE TITLE
[suggestion] Move Genesis boot.rom to /MegaDrive folder

### ISSUE THREAD

**Issue by ishtangli** [uberyoji/mister-boot-roms#6]
Since the Genesis core is being deprecated, copy boot.rom to /MegaDrive folder instead.

**Comment by uberyoji** [comment]
Not a good idea. It will interfere with legit boot rom to enable TMSS. I can copy as boot1.rom though.

**Comment by uberyoji** [comment]
But the core dont support auto booting yet 😢

**Comment by birdybro** [comment]
Sorgelig's advice is to use an MGL file instead, the autoboot of roms was a feature used before MGL was added. I have to say I kinda agree with him, the autoboot was kind of a not often used side feature.

https://mister-devel.github.io/MkDocs_MiSTer/advanced/mgl/

```xml
<mistergamedescription>
    <rbf>_Console/MegaDrive</rbf>
    <setname>MegaDrive</setname>
    <file delay="1" type="f" index="1" path="boot1.md"/>
</mistergamedescription>
```

**Comment by uberyoji** [comment]
Oh great suggestion. I could create a sub menu for this. On top of that I could start working on every other consoles such as PSX, GBA and soon N64, Saturn.

**Comment by uberyoji** [comment]
Here is my first attempt at making proper mgl. Sorry it took me a while. I started a new job and it is quite demanding.
It should add a new console folder named "Console (autoboot)". You can extract in the root (usually /media/fat).

[mister-boot-roms-mgl.zip](https://github.com/uberyoji/mister-boot-roms/files/13172222/mister-boot-roms-mgl.zip)

**Comment by NML32** [comment]
When I launch a console from your MGL file, the games folder defaults to the _mister-boot-roms folder.

**Comment by uberyoji** [comment]
This is no good indeed. I will update th mgl files to point to their respective games folder. And make sure the roms lands there as well. Thank for sharing.
Should be done tomorrow night.

**Comment by NML32** [comment]
@uberyoji Thank you for the update. The mgl files are opening in the correct games folder. :)
Mister-boot.gba is missing from the repository and zip file.

**Comment by uberyoji** [comment]
> @uberyoji Thank you for the update. The mgl files are opening in the correct games folder. :) Mister-boot.gba is missing from the repository and zip file.
[mister-boot-gba.zip](https://github.com/uberyoji/mister-boot-roms/files/13193176/mister-boot-gba.zip)

That because it is not done yet :) 
I updated the update all DB to set things up properly. Now I need to fix the archive for manual install to exclude the wip gba.
Here's the GBA file if you want to try but it is in a very very early stage :D
