### ISSUE TITLE
mister-boot.sms not booting

### ISSUE THREAD

**Issue by pa-august** [uberyoji/mister-boot-roms#7]
I installed via downlaoder.ini, all other boot roms work great except mister-boot.sms which only gives me the Sega logo.

I also manually downloaded and replaced mister-boot.sms from the Releases page with the same results.

I set and saved default settings for the sms core to make sure I hadn't changed something important.

**Comment by uberyoji** [comment]
This usually happens when the bios is enabled. Try disabling the bios in
the sms core menu.

**Comment by pa-august** [comment]
That was it - I thought I had tried flipping that off but apparently not.
