### ISSUE TITLE
Nintendo 64.mgl (type="s")

### ISSUE THREAD

**Issue by GamaBurst** [uberyoji/mister-boot-roms#9]
Hello uberyoji,
In the actual Nintendo 64.mgl

`<mistergamedescription>
    <rbf>_Console/N64</rbf>
    <file delay="1" type="s" index="1" path="mister-boot.z64"/>
</mistergamedescription>`

I think that it's supposed to be type="f" to load the mister-boot.z64 rom

type="s" is used to mount a image
type="f" is used to load rom

Greetings!

**Comment by uberyoji** [comment]
You are so right! I will fix asap.

**Comment by GamaBurst** [comment]
Thank you!! ;)
